### ISSUE TITLE
post hook

### ISSUE THREAD

**Issue by konsumer** [meandavejustice/gh-pages-deploy#17]
It would be useful to me to have a post-hook for after build and gh-pages checkout, but before commit/push.  This way I could keep source & copied files out of the static deployment.

For example:

```json
{
  "scripts": {
    "build": "browserify src/index.js -t babelify -t glslify | uglifyjs -cm > webroot/bundle.js",
    "start": "budo src/index.js:bundle.js --live -v -t babelify -t glslify -p errorify --dir webroot | garnish",
    "deploy": "gh-pages-deploy",
    "clean-source": "rimraf README.md src webroot package.json"
  },
  "gh-pages-deploy": {
    "staticpath": "webroot",
    "prep": [
      "build",
    ],
    "post": [
      "clean-source"
    ],
    "noprompt": true
  }
}
```

**Comment by meandavejustice** [comment]
I like this idea. I probably won't be able to get around to adding this anytime soon. If you feel up to it, I would be open to accepting a pull request.

**Comment by konsumer** [comment]
I'd be happy to set it up, if I have some time, today.
