### ISSUE TITLE
Deploy undefined

### ISSUE THREAD

**Issue by davislurve** [meandavejustice/gh-pages-deploy#19]
Hey,

I'm getting a strange error where it pops up saying `deploy undefined` but with no further information.  It then just hangs for ages and doesn't seem to do anything.

![screen shot 2016-03-25 at 13 10 46](https://cloud.githubusercontent.com/assets/1312905/14036600/b692ec70-f28e-11e5-92cf-22383a3c467a.png)

My `package.json` file is pretty straight forward:
```
  "scripts": {
    "scss": "node-sass --output-style compressed -o assets/css scss",
    "autoprefixer": "postcss -u autoprefixer -r assets/css/style.css",
    "build": "npm run scss && npm run autoprefixer",
    "watch": "onchange 'src/scss/**.scss' -- npm run build",
    "deploy": "gh-pages-deploy",
    "clean-source": "rimraf -f README.md scss db_rebuild.sublime-project package.json"
  },
  "devDependencies": {
    "autoprefixer": "^6.3.3",
    "gh-pages-deploy": "^0.4.1",
    "node-sass": "^3.4.2",
    "onchange": "^2.0.0",
    "postcss-cli": "^2.5.1"
  }
```

All thoughts welcome :)

**Comment by weslleyaraujo** [comment]
Same for me, does it work for you even tho?
In my case I still have to `git checkout gh-pages && git push origin gh-pages` after this

**Comment by davislurve** [comment]
Hey Weslley, 

no it doesn't work at all, my terminal just hangs.  Eventually the fans on my laptop start whirring loudly and I have to `ctrl + c` out of it

**Comment by meandavejustice** [comment]
fix published to npm
```
+ gh-pages-deploy@0.4.2
```
